parameters:
#    vizitka_user.example.class: Vizitka\UserBundle\Example

services:
#    vizitka_user.example:
#        class: %vizitka_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
