parameters:
#    vizitka_admin.example.class: Vizitka\AdminBundle\Example

services:
#    vizitka_admin.example:
#        class: %vizitka_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
